image: python:3.12.1
pipelines:
  default:
    - step:
        name: run pytest
        script: 
          - git submodule sync
          - git submodule update --init --recursive
          - cd baserepo
          - python -m pip install poetry
          - poetry install --with=dev
          - poetry run pytest -k "not test_run and not test_start_example_project and not test_get_git_version"
