image: python:3.12.1
pipelines:
  default:
    - step:
        name: run pytest
        script: 
          - git submodule sync
          - git submodule update --init --recursive
          - cd baserepo
          - pip install -r requirements.txt
          - pip install pytest
          - cd pilot
          - pytest -m "not slow and not uses_tokens and not ux_test" -k "not get_git_commit and not get_version"
