version: '2.1'
orbs:
  python: circleci/python@2.1.1
jobs:
  run-pytest:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - python/install-packages:
          app-dir: baserepo
          pkg-manager: poetry
          args: --with=dev
          pypi-cache: false
      - run:
          command: |
            cd baserepo && poetry run pytest -k "not test_run and not test_start_example_project and not test_get_git_version"
          name: Test
workflows:
  run-pytest-workflow:
    jobs:
      - run-pytest
