version: '2.1'
orbs:
  python: circleci/python@1.1.0
jobs:
  run-pytest:
    executor: python/default
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - python/install-packages:
          app-dir: baserepo
          pkg-manager: pipenv
      - python/install-packages:
          app-dir: baserepo
          pip-dependency-file: requirements.txt
          pkg-manager: pipenv
      - python/install-packages:
          app-dir: baserepo
          args: pytest
          pkg-manager: pipenv
          pypi-cache: false
      - run:
          command: |
            cd baserepo/pilot && pipenv run pytest -m "not slow and not uses_tokens and not ux_test" -k "not get_git_commit and not get_version"
          name: Test
workflows:
  run-pytest-workflow:
    jobs:
      - run-pytest
