steps:
  - command: |
      cd baserepo
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest
      cd pilot
      pytest -m "not slow and not uses_tokens and not ux_test"
