build:
  image: python:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: 
    - cd baserepo
    - pip install -r requirements.txt
    - pip install pytest
    - cd pilot
    - pytest -m "not slow and not uses_tokens and not ux_test" -k "not get_git_commit and not get_version"
  rules:
    - if: $ENABLE_PIPELINES == "true"
