build:
  image: python:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: 
    - cd baserepo
    - python -m pip install poetry
    - poetry install --with=dev
    - poetry run pytest -k "not test_run and not test_start_example_project and not test_get_git_version"
