name: run pytest
on:
  push: {}
  workflow_dispatch: {}
  
permissions:
  id-token: write

jobs:
  test:
    name: run pytest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - run: |
        cd baserepo
        python -m pip install poetry
        poetry install --with=dev
        poetry run pytest -k "not test_run and not test_start_example_project and not test_get_git_version"
