name: run pytest
on:
  push: {}
  workflow_dispatch: {}
  
permissions:
  id-token: write

jobs:
  test:
    name: run pytest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - run: |
        cd baserepo
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 ruff
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        ruff --output-format=github --select=E9,F63,F7,F82 --target-version=py37 ./pilot
        ruff --output-format=github --target-version=py37 --ignore=F401,E402,E501 ./pilot
        pip install pytest
        cd pilot
        pytest -m "not slow and not uses_tokens and not ux_test"
